backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/DataController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Response;
use common\models\Country;
use common\models\City;
use common\models\District;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class DataController extends Controller
{
    public function actionCity()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $country_id = $parents[0];
                $out = City::getAllRecords('country_id', $country_id);

                return ['output' => $out, 'selected' => ''];
            }
        }

        return ['output' => '', 'selected' => ''];
    }

    public function actionDistrict()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $country_id = $parents[0];
                $city_id = $parents[1];
                if (!empty($country_id) && !empty($city_id)) {
                    $out = District::getAllRecords('city_id', $city_id);
                    if (!empty($out)) {
                        return ['output' => $out, 'selected' => ''];
                    }
                }
            }
        }

        return ['output' => '', 'selected' => ''];
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ChangePasswordForm;
use frontend\models\ProfileForm;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'page' => [
                'class' => 'yii\web\ViewAction',
            ],
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');                   if ($user = $model->signup()) {
                Yii::$app->session->setFlash('success', 'Вы успешно зарегистрировались. Прежде, чем вы сможете войти в систему, вам придется дождаться проверки модератором. После проверки вам придет оповещение на почту, указанную при регистрации.');

                return $this->goHome();
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionProfile()
    {
        $model = new ProfileForm();
        $modelPassword = new ChangePasswordForm();

        if ($modelPassword->load(Yii::$app->request->post()) && $modelPassword->validate()) {
            if ($modelPassword->updatePassword()) {
                Yii::$app->getSession()->setFlash('success', 'Новый пароль успешно установлен.');

                return $this->redirect(['profile']);
            }
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->updateProfile()) {
                Yii::$app->getSession()->setFlash('success', 'Изменения были успешно сохранены.');

                return $this->redirect(['site/profile']);
            }
        }

        return $this->render('profile', [
            'model' => $model,
            'modelPassword' => $modelPassword,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Mangala Drive';
?>
<div class="site-index">

    <div class="body-content">

        <div class="row">
            <div class="col-lg-6">
    <div class="jumbotron">
        <h2>Для пассажиров</h2>

        <p class="lead">Текст, раскрывающий преимущества для пассажиров.</p>

        <p><a class="btn btn-lg btn-warning" href="<?= \yii\helpers\Url::to(['/ride/my-rides']) ?>">Я &mdash; пассажир</a></p>
    </div>
            </div>
            <div class="col-lg-6">
    <div class="jumbotron">
        <h2>Для водителей</h2>

        <p class="lead">Текст, раскрывающий преимущества для водителей.</p>

        <p><a class="btn btn-lg btn-success" href="<?= \yii\helpers\Url::to(['/ride/index']) ?>">Я &mdash; водитель</a></p>
    </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <?= $this->render('/site/pages/rules') ?>
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
?>
<div class="site-login">
    <p>Пожалуйста, заполните эти поля, чтобы войти в систему:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

            <div style="color:#999;margin:1em 0">
                Вы можете <?= Html::a('зарегистрировать нового пользователя', ['site/signup']) ?> или <?= Html::a('восстановить пароль', ['site/request-password-reset']) ?>.
            </div>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-default btn-orange', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/profile.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\models\User;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ProfileForm */
/* @var $modelPassword \frontend\models\ChangePasswordForm */

$this->title = 'Настройки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-success">
            <div class="panel-heading"><?= $this->title ?></div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data'],
                ]); ?>

                <?= $form->field($model, 'name') ?>

                <?= $form->field($model, 'phone') ?>

                <p><b>E-mail:</b> <?= $model->email ?></p>
                <p><b>Пол:</b> <?= User::getSexes()[$model->sex] ?></p>
                <p><b>Регион:</b> <?= $model->region ?></p>

                <?php if (!empty($model->image)): ?>
                    <div class="form-group">
                        <label class="control-label">Ваша фотография</label>
                        <div><img width="150" src="/uploads/photos/<?= $model->image ?>"/></div>
                    </div>
                <?php endif; ?>

                <div class="form-group pull-left">
                    <?= Html::submitButton('Продолжить', ['class' => 'btn btn-primary', 'name' => 'profile-button']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-success">
            <div class="panel-heading">Изменить пароль</div>
            <div class="panel-body">
                <?php $form = ActiveForm::begin(['id' => 'form-profile-2']); ?>

                <?= $form->field($modelPassword, 'passwordOld')->passwordInput() ?>

                <?= $form->field($modelPassword, 'password')->passwordInput() ?>

                <?= $form->field($modelPassword, 'passwordRepetition')->passwordInput() ?>

                <div class="form-group pull-left">
                    <?= Html::submitButton('Продолжить', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <p>Пожалуйста, заполните эти поля, чтобы восстановить пароль.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <p>Введите новый пароль:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\widgets\DepDrop;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <p>Пожалуйста, заполните эти поля, чтобы стать зарегистрированным пользователем:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

            <?= $form->field($model, 'name') ?>

            <?= $form->field($model, 'phone') ?>

            <?= $form->field($model, 'sex')->radioList(\common\models\User::getSexes()) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'country')->dropDownList(ArrayHelper::map(\common\models\Country::getAllRecords(), 'id', 'name'), ['id' => 'country-id', 'prompt' => 'Выберите..']); ?>

            <?= $form->field($model, 'city')->widget(DepDrop::class, [
                'options' => ['id' => 'city-id'],
                'pluginOptions' => [
                    'depends' => ['country-id'],
                    'placeholder' => 'Выберите..',
                    'url' => Url::to(['/data/city'])
                ]
            ]); ?>

            <?= $form->field($model, 'district')->widget(DepDrop::class, [
                'options' => ['id' => 'district-id'],
                'pluginOptions' => [
                    'depends' => ['country-id', 'city-id'],
                    'placeholder' => 'Выберите..',
                    'url' => Url::to(['/data/district'])
                ]
            ]); ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'imageFile')->fileInput() ?>

            <?= $form->field($model, 'acceptRules')->checkbox(['label' => 'Регистрируясь, я принимаю правила системы, расположенные <a href="' . Url::to(['/site/page', 'view' => 'rules']) . '">по этому постоянному адресу</a>']) ?>

            <div class="form-group">
                <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-default btn-orange', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>